parameters:
#    alx_s_blog.example.class: AlxS\BlogBundle\Example

services:
#    alx_s_blog.example:
#        class: %alx_s_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
